name: Dartalla - Site

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.7.3 ]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: '18.118.102.124'
          username: 'git'
          port: '22'
          key: ${{ secrets.SSH_KEY }}
          source: "*"
          target: '/srv/www/dartalla_site'
